### PR TITLE
Refactor UserSetting property wrapper to support Codable

### PR DESCRIPTION
**Pull request by alfogrillo**
This PR replaces the property wrapper `UserSetting` and `UserSettingRawRepresentable` with a single property wrapper called `UserPreference`.
The new property wrapper also allows to store `Codable` values in any provided storage.

### CODE REVIEW

**Comment by Velin92** [comment]
Could we add some tests for it? both for the volatile case, the storage case, for each one of this a test with PlistValues that need encoding to data and those whic don't.
We could use just a user defaults test storage

**Comment by alfogrillo** [comment]
> Amazing!
> Could we add some tests for it? both for the volatile case, the storage case, for each one of this a test with PlistValues that need encoding to data and those whic don't.
> We could use just a user defaults test storage

On it already ;)

**Review by Velin92 — APPROVED** [review]
LGTM

**Review by pixlwave — APPROVED** [review]
LGTM 👍

**Pull request merged**
