### PR TITLE
Include changelog.d and other common files in Xcode project

### PR DESCRIPTION
**Pull request by Johennes**
Fixes: #218

### Pull Request Checklist

- [x] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [x] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [ ] iPhone and iPad simulators in portrait and landscape orientations.
- [ ] Dark mode enabled and disabled.
- [ ] Various sizes of dynamic type.
- [ ] Voiceover enabled.

### CODE REVIEW

**Review by stefanceriu — COMMENTED** [review]
While I like the idea I don't love having all these files pile up on top of our project navigator. Is there a way we can drop them inside a miscellaneous folder or something?

**Comment by Johennes** [comment]
Yeah, sure I can do that. I'd also be fine with only including the `changelog.d` folder for now. I only added the others because element-ios also included these. But I don't think they're as widely used as the changelog folder.

**Comment by stefanceriu** [comment]
> sure I can do that

I'm not actually sure you **can** actually do that looking at the specs. If that's the case let's just merge is at as it.

**Review by stefanceriu — APPROVED** [review]

**Comment by Johennes** [comment]
> I'm not actually sure you **can** actually do that looking at the specs. If that's the case let's just merge is at as it.

Hm, looks like you're right. The `fileGroups` property doesn't allow any further options. So unless we want to move things around on the file system, all the items will have to be at the top level.

To limit the pain, I removed the markdown files for now and only included the `changelog.d` folder which, I think, is that one that is accessed most often.

**Pull request merged**
