### PR TITLE
Use native context menu on all platforms

### PR DESCRIPTION
**Pull request by pontaoski**
### Pull Request Checklist

- [x] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [ ] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [x] iPhone and iPad simulators in portrait and landscape orientations.
- [x] Dark mode enabled and disabled.
- [x] Various sizes of dynamic type.
- [x] Voiceover enabled.

### CODE REVIEW

**Comment by stefanceriu** [comment]
You seem to be missing a description or anything that would help us understand what prompted this. This PR changes root application functionality and UI/UX without being linked to any ticket or approved by the product and design team. Moreover it doesn't even compile.
As such, we no other option than to close it.


The actual change:

| Before | After |
|--------|-------|
|before|after|

**Comment by pontaoski** [comment]
Opened an issue to contextualise the [change](https://github.com/vector-im/element-x-ios/issues/1871).

I am afraid that I cannot do anything with the knowledge that the build fails for you as I have to substantially modify the build system in order to get it to build as a non-employee due to not having access to keys/entitlements/etc.

I attempted to cherrypick only the salient changes, but that did not work here. I have my true working copy on a branch in my fork, if that helps pin down what the issue is: https://github.com/pontaoski/element-x-ios/commit/330e182569ac87f7713896ff9adbda620e47f5a4

**Comment by stefanceriu** [comment]
> Opened https://github.com/vector-im/element-x-ios/issues/1871 to contextualise the change

Nice, thank you 👍 

>  I have to substantially modify the build system in order to get it to build as a non-employee due to not having access to keys/entitlements/etc

There must be a misunderstanding here: you can chose `Team`=`None` in the `Signing & Capabilities` which will allow you to build for any simulator

**Comment by pontaoski** [comment]
I have to adjust the `Signing & Capabilities` to my personal team as well as stripping out capabilities/entitlements that I don’t have on my developer account, as well as changing the bundle identifiers to not be the ones registered under the vector im team, etc.

**Pull request closed without merging**
