### PR TITLE
Retry send and cancel send for failed to send messages

### PR DESCRIPTION
**Pull request by Velin92**
Some screen recording of both behaviours here:

https://github.com/vector-im/element-x-ios/assets/34335419/c5e59564-6da1-42f5-80cd-f615d2a8bd80
https://github.com/vector-im/element-x-ios/assets/34335419/63e1ba2d-cc32-452b-bd88-c3b3fa814ba0

### CODE REVIEW

**Comment by callumu** [comment]
This all looks good, but can you add the header text?

**Comment by callumu** [comment]
It should say 'Your message failed to send.'

**Comment by Velin92** [comment]
> It should say 'Your message failed to send.'

@callumu 
oh yeah my bad, forgot to make the title always visible for the confirmation dialog, here it is a screenshot with the title:
simulator_screenshot_EDCC08F4-7CA2-477B-B193-86374DA8EC9E

**Comment by callumu** [comment]
> > It should say 'Your message failed to send.'
> 
> @callumu oh yeah my bad, forgot to make the title always visible for the confirmation dialog, here it is a screenshot with the title: simulator_screenshot_EDCC08F4-7CA2-477B-B193-86374DA8EC9E

Okay cool this looks good 👍

**Review by stefanceriu — APPROVED** [review]
Looks good to me too 👏

**Pull request merged**
