### PR TITLE
Update login and server selection screens

### LINKED ISSUE #632: Log in screen adjustments
### Steps to reproduce

There are some adjustments needed for the log in screen:

1. Padding increased from 'Welcome back!' to the back button
2. <del>When matrix.org is the server, we need to add 'The world's largest free server' below it as in the designs: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=6%3A7516&t=tl952FbJDyf4QCOx-1</del> - not planned as it was removed from the current apps for consistent spacing and to not favour any particular homeserver.

For the server page:

1. Padding needs to be checked for the distance from the server icon to the back arrow
2. Copy changes to just 'what is the address of your server' - I've updated the designs to match: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=6%3A8489&t=tl952FbJDyf4QCOx-1

### Outcome

See above for design links

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by pixlwave**
Fixes #632.

Additionally tidies up some uses of the old `NavigationView`, opting for `NavigationStack` instead.

| Login Screen | Server Selection Screen |
| - | - |
| Simulator Screen Shot - iPhone 14 - 2023-03-02 at 12 49 16 | Simulator Screen Shot - iPhone 14 - 2023-03-02 at 12 49 23 |

### CODE REVIEW

**Review by stefanceriu — APPROVED** [review]
Good stuff 👍

**Comment by callumu** [comment]
Some comments:

1. Copy should be 'Email or username'
2. Could you check the size of the server icon and match it to the design?
3. The copy size of 'What is the address of your server?' should be smaller and 15px

**Comment by pixlwave** [comment]
@callumu Updated (using just `Username` as discussed as signing in with an email doesn't work).

**Comment by callumu** [comment]
This looks great, thanks

**Review by Velin92 — APPROVED** [review]
LGTM!

**Pull request merged**
