### PR TITLE
Ignore background images in OnboardingBackgroundView for VoiceOver users [Bugfix]

### PR DESCRIPTION
**Pull request by sempruijs**
### Pull Request Checklist

- [x] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [x] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [x] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [x] iPhone and iPad simulators in portrait and landscape orientations.
- [x] Dark mode enabled and disabled.
- [x] Various sizes of dynamic type.
- [x] Voiceover enabled.

In the welcome screen when you boot the app for the first time, there are moving images that are not useful for VoiceOver users. This pr ignores them.

I do not know the flow of adding lines to the change log, so if someone could explain how that works, I would be glad :)
(It's my first time here)

### CODE REVIEW

**Comment by sempruijs** [comment]
Signed-off-by: Sem Pruijs <sem@pruijs.net>

**Comment by pixlwave** [comment]
Thanks for your contribution @sempruijs, this PR looks good to me. If you could update your changelog filename to be `pr-658.bugfix`, I'll get this merged.

**Comment by sempruijs** [comment]
Yesss did it 🙌

**Comment by pannie** [comment]
LGTM

**Pull request merged**
