### PR TITLE
iOS: Removing event id links

### PR DESCRIPTION
**Pull request by Velin92**
Event Identifiers were actually recognised as links, however this behaviour does not actually exist on any other version of the app, (like El-Web) and even if they were recognised as link, they were not handled (the link just contained the event identifier, which is actually not a valid URL resulting in an untappable link).

This also caused a bug where any $ amount was always being seen as an untappable link:
https://github.com/vector-im/element-x-ios/issues/500

### CODE REVIEW

**Review by stefanceriu — CHANGES_REQUESTED** [review]
Good catch but I don't think we should remove the mxid regex parser. It feels like something that we will definitely need in the future and it's already well tested.

What might be interesting to look into is whether it detecting money is valid or if there's a bug somewhere.

**Comment by Velin92** [comment]
> Good catch but I don't think we should remove the mxid regex parser. It feels like something that we will definitely need in the future and it's already well tested.
> 
> What might be interesting to look into is whether it detecting money is valid or if there's a bug somewhere.

I see, however even if we have the link detector for event id, the link actually does nothing even on valid event identifiers. Maybe we should keep the code for the future, but remove the check of converting these identifiers to links? Since even with valid ones it's going to create untappable links

**Comment by stefanceriu** [comment]
> but remove the check of converting these identifiers to links

I'm good with removing the line from the AttributedStringBuilder, I just want to keep what's in `MatrixEntityRegex` and friends.

And after another look, we should definitely keep the check from `permalinkTo(eventIdentifier`, I missed that in my initial review

**Comment by Velin92** [comment]
> > but remove the check of converting these identifiers to links
> 
> I'm good with removing the line from the AttributedStringBuilder, I just want to keep what's in `MatrixEntityRegex` and friends.
> 
> And after another look, we should definitely keep the check from `permalinkTo(eventIdentifier`, I missed that in my initial review

done! commented the code and added a comment on top of it, so we could reuse it later when we actually know what to do with such links

**Review by stefanceriu — APPROVED** [review]
great 👏

**Pull request merged**
