### PR TITLE
Composer and RTE polish

### PR DESCRIPTION
**Pull request by alfogrillo**
This PR
- Updates the UI for the composer and the Rich Text Editor
- Updates all the related ui tests

| Light | Dark |
| --- | --- |
|s1|s1-dark|
|s2|s2-dark|

### CODE REVIEW

**Comment by callumu** [comment]
This looks good 👍

When will I be able to test it on device?

**Comment by alfogrillo** [comment]
> This looks good 👍
> 
> When will I be able to test it on device?

As soon as it gets merged. Hopefully on Monday

**Comment by manuroe** [comment]
FYI, it is possible to have a build available on diawi from a PR. You just need to add the label `X-Trigger-PR-Build` to the PR

**Comment by alfogrillo** [comment]
> FYI, it is possible to have a build available on diawi from a PR. You just need to add the label `X-Trigger-PR-Build` to the PR

@callumu I triggered a diawi build like Manu suggested. 
Use it if you want to have an early look.
The QR code will appear in the PR when the build process ends.

**Review by stefanceriu — APPROVED** [review]
lgtm! 👏

**Comment by callumu** [comment]
This looks pretty good but I have a couple of comments:

1. There are issues with the inline code and code block colours
2. There is too much space between the keyboard and the composer. What is the current spacing here?

**Comment by alfogrillo** [comment]
> This looks pretty good but I have a couple of comments:
> 
> 1. There are issues with the inline code and code block colours
> 2. There is too much space between the keyboard and the composer. What is the current spacing here?

1. Background color has been changed to `gray100`, no other changes has been introduced here
2. Discussed privately and addressed as a part of this PR

**Pull request merged**
